### PR TITLE
Refactoring interim results to use generics, and separating tests

### PR DESCRIPTION
**Pull request by tamasvajk**

### CODE REVIEW

**Comment by tamasvajk** [comment]
@jochenvanwylick Can you have a look if everything works on your side with this refactoring? Thanks.

**Comment by jochenvanwylick** [comment]
@tamasvajk - Will do, give me 10 minutes

**Comment by jochenvanwylick** [comment]
@tamasvajk - yup, looks all fine to me!

**Comment by tamasvajk** [comment]
@jochenvanwylick Thanks for checking it out. I just pushed these changes to NuGet. You can grab it here: https://www.nuget.org/packages/SkyScanner/1.3.0

**Pull request merged**
