### PR TITLE
Removed api key values + added constructor argument checks

### PR DESCRIPTION
**Pull request by jochenvanwylick**
Hey Tamasvajk,

your API keys were in the app.config. I thought you might want to get rid of those since they're on the public internet. So I did that for you. Also - I added a constructor argument check to help people that do a fresh clone to get started.

Cheers,
Jochen

### CODE REVIEW

**Comment by tamasvajk** [comment]
@jochenvanwylick Thanks for the PR. The API key was left in the app.configs on purpose. Without them you couldn't use the sample program, and the tests. It is not a security issue, as this is the public API key provided by SkyScanner: check their [test harness website](http://business.skyscanner.net/portal/en-GB/Documentation/FlightsLivePricingQuickStart)

If you roll the config file changes back, I'll merge your PR. Thanks

**Comment by jochenvanwylick** [comment]
Ah Thanks - didn't catch that. I'll put it back first thing tomorrow.

**Comment by jochenvanwylick** [comment]
Hey Tamasvajk,

I replaced the API keys - fixes some of the dates in the console test app to be relative to DateTime.Now ( so they won't break in the future ) and downgraded to .NET Framework version to 4.5 from 4.5.1 ( in order to be compatible with my solution ).

What do you think?

**Comment by tamasvajk** [comment]
@jochenvanwylick Seems good. Can you double check that the API key is the test one provided by SkyScanner? It's not the same as before. After that I'll merge it to master, and publish it to nuget.org.

**Comment by jochenvanwylick** [comment]
@tamasvajk @tvsonar - Implemented your feedback. Thanks for the review!

**Comment by tamasvajk** [comment]
@jochenvanwylick Thanks for this contribution, I merged this PR to the master. I did a rebase on your branch first, so GitHub doesn't pick up that this PR has been merged. (The commits are there, it's only the PR.) 

Also, I've published this version (version 1.2.0) to nuget.org: https://www.nuget.org/packages/SkyScanner/1.2.0

**Pull request closed without merging**
