### PR TITLE
"Unknown" enum member for JourneyMode

### PR DESCRIPTION
**Pull request by Temp1ar**
Hi, thanks for great API implementation.

Today I got bunch of results from Skyscanner with Unknown for JourneyMode enum, and get many Json deserialization exceptions as well.

Should I write to skyscanner support to clarify this?

Have sample requests written by fiddler as proofs :)

### CODE REVIEW

**Comment by tamasvajk** [comment]
@Temp1ar yes, could you ask the SkyScanner team if this was a newly introduced value or not? Also, can you add a unit test where this `Unknown` is returned. Thanks.

**Comment by KirillShlenskiy** [comment]
Wish I'd seen this before I went creating my own fork.

@tamasvajk, SYD-sky -> JNGO-sky queries consistently return results containing JourneyMode.Unknown. I've adde a unit test here:

https://github.com/KirillShlenskiy/SkyScanner/commit/79757499469a824b9961e28beb0feb3030f4ce4c

**Comment by Temp1ar** [comment]
Here is official answer from SkyScanner support

> After some consulting this with our Flights API Team. 
> We can confirm that this field can be ignored.
> 
> We have updated our API regarding this:
> https://support.business.skyscanner.net/hc/en-us/articles/209228365
> 
> We will also update our docs to avoid confusion in the future.
> 
> Thanks a lot for bringing this up!
> 
> Regards,
> B2B Support

**Comment by Temp1ar** [comment]
So, i can add Kirill's test to my PR if he does not mind or we can close this PR and ask for Kirills fork.

**Comment by KirillShlenskiy** [comment]
I'd be happy to contribute either way.

The test is a bit flaky in that it does not contain any problem-specific assertions. However, if you remove the `JourneyMode.Unknown` declaration, it fails reliably.

@tamasvajk, let me know if you think I can/should improve the test in question.

**Comment by tamasvajk** [comment]
I think adding the test (a test) to the PR would be the cleanest. Thanks.

**Comment by Temp1ar** [comment]
Done.

**Comment by tamasvajk** [comment]
Thanks, and sorry for the delay. I'm planning to merge, and then release the nuget next week.

**Pull request merged**
