### PR TITLE
Issue #18 Add search overloads that take in CancellationToken

### LINKED ISSUE #18: Add search overloads that take in CancellationToken
Once a search is fired off - there is no way to cancel the search process. I would suggest we add an overload to the search methods that takes in a cancellation token - which will stop the polling process in the background.

We're seeing a bunch of users that fire off wrong searches or decide to change their search mid-search. In order to save resources - I would like to be able to cancel the process.

Something along the lines of 

`Task<List<Itinerary>> QueryFlight(FlightQuerySettings flightQuerySettings, CancellationToken token);`

### PR DESCRIPTION
**Pull request by tamasvajk**
Fixes #18

### CODE REVIEW

**Comment by tamasvajk** [comment]
@jochenvanwylick Could you check if this PR works for you, and as expected? Thanks

**Comment by tamasvajk** [comment]
@jochenvanwylick Sorry to bother you again. Are you planning on reviewing this PR?

**Comment by jochenvanwylick** [comment]
Hi @tamasvajk - sorry for the late response. I'm checking right now!

**Comment by tamasvajk** [comment]
@jochenvanwylick Thanks. If you have time, you could check the other one too: #19

**Comment by jochenvanwylick** [comment]
Yeah - aswesome. It would have been fine to finish the ongoing HTTP call and just stop the polling with the token - but you pass it all the way down to `GetAsync()` which is even nicer. Cool - thanks!

**Pull request merged**
